# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sonar < Formula
  desc ""
  homepage ""
  version "1.7.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bi-zone/sonar/releases/download/v1.7.0/sonar_1.7.0_Darwin_x86_64.tar.gz"
      sha256 "a5918329e8ff993e6121ae4caf47d3935e0b68dde77c40630f00d1a098990595"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/bi-zone/sonar/releases/download/v1.7.0/sonar_1.7.0_Linux_x86_64.tar.gz"
      sha256 "c3cc3995122d34176454af9a6eade8e33b291130465bb0267f8b6f03231abb4f"
    end
  end

  def install
    bin.install "sonar"
  end
end
