# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sonar < Formula
  desc ""
  homepage ""
  version "1.7.3"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bi-zone/sonar/releases/download/v1.7.3/sonar_1.7.3_Darwin_x86_64.tar.gz"
      sha256 "c7d7974d8e40029a595f0068f7d67bc2de6041a90e7bdfa347a6a7b8922b80bb"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/bi-zone/sonar/releases/download/v1.7.3/sonar_1.7.3_Linux_x86_64.tar.gz"
      sha256 "6299c9923beb43fe3329744db72738babfe80aa4c26ede590d46e28ef4ef536d"
    end
  end

  def install
    bin.install "sonar"
  end
end
